# Puerto donde corre la app
server.port=8080

spring.datasource.url=jdbc:postgresql://db.zieavlvrzeqqsecgnpqb.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=TU_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect