# Puerto donde corre la app
server.port=8080

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.zxtkcikadwukvwdymgmi
spring.datasource.password=Cembal1234**
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Evita prepared statements con pooler
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===============================
# HIKARI CONNECTION POOL
# ===============================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=600000